DROP SCHEMA IF EXISTS proyectotienda;
CREATE DATABASE proyectotienda character set utf8mb4 collate utf8mb4_general_ci;
USE proyectotienda;

CREATE TABLE ROLES (
	ROLID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(255) NOT NULL
);

CREATE UNIQUE INDEX INDX_ROLES_PK
ON ROLES (ROLID);

INSERT INTO ROLES (NOMBRE) VALUES ('ADMIN');
INSERT INTO ROLES (NOMBRE) VALUES ('CLIENTE');
commit;


CREATE TABLE USUARIOS (
	CORREO VARCHAR(255) NOT NULL PRIMARY KEY,
	NOMBRE VARCHAR(100) NOT NULL,
	APELLIDO1 VARCHAR(100) NOT NULL,
	APELLIDO2 VARCHAR(100) NOT NULL,
	TELEFONO VARCHAR(9) NOT NULL,
	DIRECCION VARCHAR(255) NOT NULL,
	ROLID INT DEFAULT 2,
	FOREIGN KEY (ROLID) REFERENCES ROLES(ROLID)
);

CREATE UNIQUE INDEX INDX_USUARIOS_PK
ON USUARIOS (CORREO);

INSERT INTO USUARIOS (CORREO, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, DIRECCION) VALUES ('anonimo@est.com','anonimo','anonimo','anonimo','00000000','anonimo');
INSERT INTO USUARIOS (CORREO, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, DIRECCION, ROLID) VALUES ('joviedo@test.com','Joshua','Oviedo','Arias','88887777','San Pablo de Heredia',1);
INSERT INTO USUARIOS (CORREO, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, DIRECCION) VALUES ('dalvarado@test.com','Daniel','Alvarado','Vega','12341234','Cartago donde el ciento se devuelve');
INSERT INTO USUARIOS (CORREO, NOMBRE, APELLIDO1, APELLIDO2, TELEFONO, DIRECCION) VALUES ('maria@test.com','maria','Espinoza','Delgado','78945612','test de prueba con algunos ingresos de datos');
commit;


CREATE TABLE PRODUCTOS (
	PRODUCTOID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(150) NOT NULL,
	DESCRIPCION VARCHAR(255) NOT NULL,
	PRECIO DECIMAL(10,2) NOT NULL,
	CANTIDAD INT DEFAULT 0,
	IMAGEN longblob
);

CREATE UNIQUE INDEX INDX_PRODUCTOS_PK
ON PRODUCTOS (PRODUCTOID);
	
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CANTIDAD) VALUES ('Bowl Pequeño','Bowl Pequeño',15000,10);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CANTIDAD) VALUES ('Bowl Mediano','Bowl Mediano',25000,7);
INSERT INTO PRODUCTOS (NOMBRE, DESCRIPCION, PRECIO, CANTIDAD) VALUES ('Bowl Grande','Bowl Grande',35000,9);
commit;


CREATE TABLE FACTURA (
	FACTURAID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	CREADO DATETIME DEFAULT NOW(),
	SUBTOTAL DECIMAL(10,2) DEFAULT 0,
	DONACION DECIMAL(10,2) DEFAULT 0,
	TOTAL DECIMAL(10,2) DEFAULT 0,
	CORREO VARCHAR(255) NOT NULL,
	FOREIGN KEY (CORREO) REFERENCES USUARIOS(CORREO)
);

CREATE UNIQUE INDEX INDX_FACTURA_PK
ON FACTURA (FACTURAID);


CREATE TABLE DetalleFactura (
	detFACTURAID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	precioUnitario DECIMAL(10,2) DEFAULT 0,
	precioTotal DECIMAL(10,2) DEFAULT 0,
	productoid INT NOT NULL,
	facturaid INT NOT NULL,
	FOREIGN KEY (productoid) REFERENCES PRODUCTOS(productoid),
	FOREIGN KEY (facturaid) REFERENCES FACTURA(facturaid)
);

CREATE UNIQUE INDEX INDX_DetalleFactura_PK
ON DetalleFactura (detFACTURAID);

CREATE TABLE personalizado (
	personalizadoid INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	NOMBRE VARCHAR(150) NOT NULL,
	DESCRIPCION VARCHAR(255),
	IMAGEN longblob,
	productoid INT NOT NULL,
	facturaid INT NOT NULL,
	FOREIGN KEY (productoid) REFERENCES PRODUCTOS(productoid),
	FOREIGN KEY (facturaid) REFERENCES FACTURA(facturaid)
);

CREATE UNIQUE INDEX INDX_personalizado_PK
ON personalizado (personalizadoid);

commit;



CREATE TABLE `carrito` (                                                                      
           `CARRITOID` INT(100)NOT NULL AUTO_INCREMENT,     
           `PRODUCTOID` INT(100) NOT NULL, 
           `PRECIO` DECIMAL(10,2)  NOT NULL,
            PRIMARY KEY (`CARRITOID`),
            KEY `FK_PRODUCTOID` (`PRODUCTOID`),                                                             
           KEY `FK_PRECIO` (`PRECIO`),                                                   
           CONSTRAINT `FK_PRODUCTOID` FOREIGN KEY (`PRODUCTOID`) REFERENCES `productos` (`PRODUCTOID`),          
           CONSTRAINT `FK_PRECIO` FOREIGN KEY (`PRODUCTOID`) REFERENCES `productos` (`PRODUCTOID`)  
         );
         